export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BERTH_PLAN_NOT_FOUND: "BERTH_PLAN_NOT_FOUND",
  BERTH_PLAN_ALREADY_APPROVED: "BERTH_PLAN_ALREADY_APPROVED",
  BERTH_PLAN_NOT_APPROVABLE: "BERTH_PLAN_NOT_APPROVABLE",
  BERTH_TIME_OVERLAP: "BERTH_TIME_OVERLAP",
  YARD_SLOT_NOT_FOUND: "YARD_SLOT_NOT_FOUND",
  YARD_SLOT_OCCUPIED: "YARD_SLOT_OCCUPIED",
  YARD_SLOT_LOCKED: "YARD_SLOT_LOCKED",
  APPROVAL_RACE_LOST: "APPROVAL_RACE_LOST"
} as const;

/** 错误码 -> 详情页失败原因区块使用的简短归类标题。 */
export const ERROR_CODE_TITLES: Record<string, string> = {
  BERTH_PLAN_NOT_FOUND: "计划不存在",
  BERTH_PLAN_ALREADY_APPROVED: "重复审批",
  BERTH_PLAN_NOT_APPROVABLE: "当前状态不可审批",
  BERTH_TIME_OVERLAP: "泊位时段重叠",
  YARD_SLOT_NOT_FOUND: "箱位不存在",
  YARD_SLOT_OCCUPIED: "箱位已占用",
  YARD_SLOT_LOCKED: "箱位被锁定",
  RBAC_DENIED: "调度权限不足",
  VALIDATION_FAILED: "参数不合法",
  APPROVAL_RACE_LOST: "并发冲突"
};
