export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BERTH_PLAN_NOT_FOUND: "BERTH_PLAN_NOT_FOUND",
  BERTH_PLAN_ALREADY_APPROVED: "BERTH_PLAN_ALREADY_APPROVED",
  BERTH_PLAN_NOT_APPROVABLE: "BERTH_PLAN_NOT_APPROVABLE",
  BERTH_TIME_OVERLAP: "BERTH_TIME_OVERLAP",
  YARD_SLOT_NOT_FOUND: "YARD_SLOT_NOT_FOUND",
  YARD_SLOT_OCCUPIED: "YARD_SLOT_OCCUPIED",
  YARD_SLOT_LOCKED: "YARD_SLOT_LOCKED",
  APPROVAL_RACE_LOST: "APPROVAL_RACE_LOST"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
